### PR TITLE
small project(reaction tester game)

### PR DESCRIPTION
**Pull request by garimasingh22**
issue no - #1 
its a simple game created in html,css,js
it gives the reaction time taken to click a random color block at any point of the screen

### CODE REVIEW

**Review by sakshamsingh01 — APPROVED** [review]
Hi @garimasingh22! It was nice to see your project. I'm approving and merging.

Make sure to add your name in contributors.md, Thanks!

**Comment by garimasingh22** [comment]
@SakshamSingh-v2 hey, I saw u removed hacktoberfest label will that cause any problem?

**Comment by sakshamsingh01** [comment]
@garimasingh22  No there shouldn't be any problems as such if your PR is approved on Hacktoberfest Dashboard. But I'm adding an Hacktoberfest-accepted label for assurance.

**Comment by garimasingh22** [comment]
@SakshamSingh-v2 thank you:)

**Pull request merged**
