### PR TITLE
First ML Project

### PR DESCRIPTION
**Pull request by Harshalszz**
First ML Project
Python/Motion_detection/Detection.py
Python/Motion_detection/output.avi

### CODE REVIEW

**Review by sakshamsingh01 — CHANGES_REQUESTED** [review]
Hi @Harshalszz . It was really good to see your project.
Please add a readme.md file describing about your project so that others can know. :-)

**Comment by Harshalszz** [comment]
@SakshamSingh-v2  I have added README.md file for motion detection .

**Comment by Harshalszz** [comment]
@SakshamSingh-v2 Hey! can you please take a look at my PR.

**Comment by sakshamsingh01** [comment]
Great! @Harshalszz I'm merging

**Pull request merged**
